//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UsersProfileId { get; set; }
        public Nullable<System.Guid> Photo { get; set; }
        public string Content { get; set; }
        public Nullable<int> Estimation { get; set; }
    
        public virtual Image Images { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
