
drop profile MANAGER_PROFILE CASCADE;
CREATE PROFILE MANAGER_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 20
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

DROP USER MANAGER;
CREATE USER manager IDENTIFIED BY qwerty
    DEFAULT TABLESPACE COURSE_TS
    TEMPORARY TABLESPACE COURSE_TS_TEMP
    PROFILE MANAGER_PROFILE
    QUOTA UNLIMITED ON COURSE_TS;

DROP ROLE MANAGER_ROLE;
CREATE ROLE MANAGER_ROLE;

GRANT
    CREATE SESSION
TO MANAGER_ROLE;

grant select on ADMIN.Reviews to staff_role;--
grant select on ADMIN.userlogin to staff_role;--

GRANT EXECUTE ON admin.admin_package TO MANAGER_ROLE;
GRANT EXECUTE ON admin.general_package TO MANAGER_ROLE;


GRANT MANAGER_ROLE TO MANAGER;
REVOKE MANAGER_ROLE FROM MANAGER;

