drop profile CUSTOMER_PROFILE CASCADE;
CREATE PROFILE CUSTOMER_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 20
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

DROP USER CUSTOMER;
CREATE USER customer IDENTIFIED BY qwerty
    DEFAULT TABLESPACE COURSE_TS
    TEMPORARY TABLESPACE COURSE_TS_TEMP
    PROFILE CUSTOMER_PROFILE
    QUOTA UNLIMITED ON COURSE_TS;

DROP ROLE CUSTOMER_ROLE;
CREATE ROLE CUSTOMER_ROLE;

GRANT
    CREATE SESSION
TO CUSTOMER_ROLE;
grant select on goods to customer_role;
--revoke select on goods from customer_role;
GRANT EXECUTE ON admin.user_package TO CUSTOMER_ROLE;
GRANT EXECUTE ON admin.general_package TO CUSTOMER_ROLE;


GRANT CUSTOMER_ROLE TO CUSTOMER;
REVOKE CUSTOMER_ROLE FROM CUSTOMER;

select * from user_objects where OBJECT_NAME like '%PROCEDURES_PACKAGES%' and object_type ='PACKAGE';
