
drop profile STAFF_PROFILE CASCADE;
CREATE PROFILE STAFF_PROFILE LIMIT
    PASSWORD_LIFE_TIME 180
    SESSIONS_PER_USER 20
    FAILED_LOGIN_ATTEMPTS 7
    PASSWORD_LOCK_TIME 1
    PASSWORD_REUSE_TIME 10
    PASSWORD_GRACE_TIME DEFAULT
    CONNECT_TIME 180
    IDLE_TIME 30;

DROP USER STAFF;
CREATE USER staff IDENTIFIED BY qwerty
    DEFAULT TABLESPACE COURSE_TS
    TEMPORARY TABLESPACE COURSE_TS_TEMP
    PROFILE STAFF_PROFILE
    QUOTA UNLIMITED ON COURSE_TS;

DROP ROLE STAFF_ROLE;
CREATE ROLE STAFF_ROLE;

GRANT
    CREATE SESSION
TO STAFF_ROLE;

grant select on ADMIN.Reviews to staff_role;
grant select on ADMIN.userlogin to staff_role;

GRANT EXECUTE ON admin.staff_package TO STAFF_ROLE;
GRANT EXECUTE ON admin.general_package TO STAFF_ROLE;


GRANT STAFF_ROLE TO STAFF;
REVOKE STAFF_ROLE FROM STAFF;

