select * from USER_INDEXES;
drop index USERPROFILE_USERLOGINID_INDEX;
drop index USERPROFILE_USERPOINTID_INDEX;
--userprofile table
create index USERPROFILE_USERLOGINID_INDEX on USERPROFILE(USERLOGINID);
create index USERPROFILE_USERPOINTID_INDEX on USERPROFILE(USERPOINTID);

--Orders table
drop index ORDERS_CUSTOMERPROFILEID_INDEX ;
drop index ORDERS_EXCECUTORPROFILEID_INDEX;
drop index ORDERS_USERLCATIONID_INDEX;
drop index ORDERS_DELIVERYLOCATIONID_INDEX;
drop index ORDERS_STATUS_INDEX;
---------------------
create index ORDERS_CUSTOMERPROFILEID_INDEX on ORDERS(CUSTOMERPROFILEID);
create index ORDERS_EXCECUTORPROFILEID_INDEX on ORDERS(EXCECUTORPROFILEID);
create index ORDERS_USERLCATIONID_INDEX on ORDERS(USERLOCATIONID);
create index ORDERS_DELIVERYLOCATIONID_INDEX on ORDERS(DELIVERYLOCATIONID);
create index ORDERS_STATUS_INDEX on ORDERS(STATUS);


--GoodsToOrder table
drop index GOODSTOORDER_ORDERID_INDEX;
drop index GOODSTOORDER_GOODSID_INDEX;
---------------------
create index GOODSTOORDER_ORDERID_INDEX on GOODSTOORDER(ORDERID);
create index GOODSTOORDER_GOODSID_INDEX on GOODSTOORDER(GOODSID);

--Reviews table
drop index REVIEWS_USERPROFILEID_INDEX;
--------------------
create index REVIEWS_USERPROFILEID_INDEX on REVIEWS(USERPROFILEID);


--History table
drop index HISTORY_ORDERID_INDEX;
-----------------------------
create index HISTORY_ORDERID_INDEX on HISTORY(ORDERID);

--POINTS
drop index POINTS_TYPE_INDEX;
-----------------------
create index POINTS_TYPE_INDEX on POINTS(TYPE);

--USERLOGIN
drop index USERLOGIN_ROLE_INDEX;
------------------
create index USERLOGIN_ROLE_INDEX on USERLOGIN(ROLE);

--GOODS
drop index GOODS_NAME_INDEX;
------------------
create index GOODS_NAME_INDEX on GOODS(NAME);
